In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("concrete_data.csv")
df

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [31]:
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000

In [32]:
df.isnull()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
1025,False,False,False,False,False,False,False,False
1026,False,False,False,False,False,False,False,False
1027,False,False,False,False,False,False,False,False
1028,False,False,False,False,False,False,False,False
1029,False,False,False,False,False,False,False,False

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cement              1030 non-null   float64
 1   Blast Furnace Slag  1030 non-null   float64
 2   Fly Ash             1030 non-null   float64
 3   Water               1030 non-null   float64
 4   Superplasticizer    1030 non-null   float64
 5   Coarse Aggregate    1030 non-null   float64
 6   Fine Aggregate      1030 non-null   float64
 7   Age                 1030 non-null   int64
dtypes: float64(7), int64(1)
memory usage: 64.5 KB

In [24]:
df.columns

Index(['Cement', 'Blast Furnace Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'Age'],
      dtype='object')

In [34]:
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [62]:
x= df.drop(['Cement'],axis=1)

In [63]:
from sklearn.model_selection import KFold

In [64]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42, test_size = 0.2)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(824, 7)
(824,)
(206, 7)
(206,)

In [68]:
from sklearn.linear_model import *
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import confusion_matrix,classification_report

In [69]:
lreg=LinearRegression()
lreg.fit(x_train,y_train)
y_pred=lreg.predict(x_test)

rmae = mean_absolute_error(y_test,y_pred)
rmse = mean_squared_error(y_test,y_pred)
rrmse= np.sqrt(mean_squared_error(y_test,y_pred))
rr2  = r2_score(y_test,y_pred)

print("mean absolute error:",rmae)
print("mean squared error:",rmse)
print("root mean squared error:",rmse)
print("r2-score:",rr2)

mean absolute error: 8.674174310665512
mean squared error: 113.83712221932531
root mean squared error: 113.83712221932531
r2-score: 0.5582175790319944

In [72]:
rid = Ridge()
rid.fit(x_train,y_train)
y_pred=rid.predict(x_test)

Rmae = mean_absolute_error(y_test,y_pred)
Rmse = mean_squared_error(y_test,y_pred)
Rrmse= np.sqrt(mean_squared_error(y_test,y_pred))
Rr2  = r2_score(y_test,y_pred)

print("mean absolute error:",Rmae)
print("mean squared error:",Rmse)
print("root mean squared error:",Rrmse)
print("r2-score:",Rr2)

mean absolute error: 8.674177175148397
mean squared error: 113.83718934411957
root mean squared error: 10.669451220382404
r2-score: 0.558217318532137

In [73]:
las = Lasso()
las.fit(x_train,y_train)
y_pred=las.predict(x_test)

lmae = mean_absolute_error(y_test,y_pred)
lmse = mean_squared_error(y_test,y_pred)
lrmse= np.sqrt(mean_squared_error(y_test,y_pred))
lr2  = r2_score(y_test,y_pred)

print("mean absolute error:",lmae)
print("mean squared error:",lmse)
print("root mean squared error:",lrmse)
print("r2-score:",lr2)

mean absolute error: 8.675401976296813
mean squared error: 113.91125936717727
root mean squared error: 10.67292178211652
r2-score: 0.5579298654283547

In [74]:
data = [['Linear',rmae,rmse,rrmse,rr2], ['Lasso',Rmae,Rmse,Rrmse,Rr2], ['Ridge',lmae,lmse,lrmse,lr2]]
summary = pd.DataFrame(data, columns=['Model', 'Mean Absolute Error','Mean Squred Error','Root Mean Squared Error','R2 Score'])

summary

,Model,Mean Absolute Error,Mean Squred Error,Root Mean Squared Error,R2 Score
0,Linear,8.674174,113.837122,10.669448,0.558218
1,Lasso,8.674177,113.837189,10.669451,0.558217
2,Ridge,8.675402,113.911259,10.672922,0.557930

In [78]:
from tensorflow.keras import Model
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.losses import MeanSquaredLogarithmicError
from geopy.format import units
from sklearn.metrics import mean_squared_error
from tensorflow.keras.optimizers import Adam

In [76]:
def build_model_using_sequential():
  model = Sequential([
    Dense(units = 128, kernel_initializer='normal', activation='relu'),
    Dense(units = 64, kernel_initializer='normal', activation='relu'),
    Dense(units = 32, kernel_initializer='normal', activation='relu'),
    Dense(1, kernel_initializer='normal')
  ])
  return model
# build the model
model = build_model_using_sequential()

In [80]:
learning_rate = 0.01

msle = MeanSquaredLogarithmicError()
model.compile(
    loss=msle,
    optimizer=Adam(learning_rate=learning_rate),
    metrics=[msle]
)
# train the model
history = model.fit(
    x_train,
    y_train,
    epochs=10,
    batch_size=50
)

Epoch 1/10
17/17 [==============================] - 2s 3ms/step - loss: 12.4248 - mean_squared_logarithmic_error: 12.4463
Epoch 2/10
17/17 [==============================] - 0s 3ms/step - loss: 12.4248 - mean_squared_logarithmic_error: 12.4263
Epoch 3/10
17/17 [==============================] - 0s 2ms/step - loss: 12.4249 - mean_squared_logarithmic_error: 12.4268
Epoch 4/10
17/17 [==============================] - 0s 3ms/step - loss: 12.4248 - mean_squared_logarithmic_error: 12.4080
Epoch 5/10
17/17 [==============================] - 0s 3ms/step - loss: 12.4248 - mean_squared_logarithmic_error: 12.4096
Epoch 6/10
17/17 [==============================] - 0s 2ms/step - loss: 12.4249 - mean_squared_logarithmic_error: 12.4274
Epoch 7/10
17/17 [==============================] - 0s 2ms/step - loss: 12.4248 - mean_squared_logarithmic_error: 12.4299
Epoch 8/10
17/17 [==============================] - 0s 3ms/step - loss: 12.4248 - mean_squared_logarithmic_error: 12.4345
Epoch 9/10
17/17 [==============================] - 0s 3ms/step - loss: 12.4248 - mean_squared_logarithmic_error: 12.4535
Epoch 10/10
17/17 [==============================] - 0s 2ms/step - loss: 12.4249 - mean_squared_logarithmic_error: 12.4558